### Q1. If you have any, what are your choices for increasing the comparison between different figures on the same graph?
- using seaborn's kde-plot we can increase the comparison different figures.
- Matplotlib provides a convenient method called subplots which also increases the graph comparison.

### Q2. Can you explain the benefit of compound interest over a higher rate of interest that does not compound after reading this chapter?
Benifit of Compound interest is that its interest is calculated on both principal amount and previously added interest amount that is the reason it grows faster, whereas in simple interest interest is calculated only on principal amount and does not add previous interest.

### Q3. What is a histogram, exactly? Name a numpy method for creating such a graph.
- Histogram is a bucket like bar chart where each bar has a specific range in which the count is represented as a bar.
- In the X-axis range is defined and in the Y-axis count is represented.
- numpy.histogram() is the function in numpy for histogram.

### Q4. If necessary, how do you change the aspect ratios between the X and Y axes?
By using figure() function from the matplot.pyplot library to scale the graph.

### Q5. Compare and contrast the three types of array multiplication between two numpy arrays: dot product, outer product, and regular multiplication of two numpy arrays.

In [2]:
import numpy as np
arr1 = np.array([[1,1,1], [2,2,2], [3,3,3]])
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [3]:
arr1 * arr2

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

The above one is simple multiplication. ex : result at [0][0] = arr1[0][0]* arr2[0][0] 

In [4]:
np.dot(arr1, arr2)

array([[12, 15, 18],
       [24, 30, 36],
       [36, 45, 54]])

The above one is metrix multiplication.

In [6]:
np.outer(arr1, arr2)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27]])

In the above multiplication each element of first array is multiplied with each element of second array. 

### Q6. Before you buy a home, which numpy function will you use to measure your monthly mortgage payment?
np.pmt() function we will be using in order to calculate monthly mortgage payment before you purchase a house.

### Q7. Can string data be stored in numpy arrays? If so, list at least one restriction that applies to this data.
- Yes, an array can store the string.
- The limitation which imposed on the string data is, whenever we store the data of string dtype then it should should keep in mind that the string which is having the maximum length is the limit.